title: Dataform Docs
email: team@dataform.co
description: >-
  Documentation for Dataform.
baseurl: ""
url: "https://docs.dataform.co"
twitter_username: dataform
github_username:  tada-science

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

theme: minima
plugins:
  - jekyll-feed

collections:
  guides:
    output: true
    permalink: /guides/:path/
  reference:
    output: true
    permalink: /reference/:path/
